version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    stdin_open: true
