version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    stdin_open: true

#  nginx:
#    restart: always
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile.dev
#    ports:
#      - "3000:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mysql:
    build:
      context: database/mysql
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql/mysql_data:/var/lib/mysql
      - ./database/mysql/sqls/:/docker-entrypoint-initdb.d/

