# Compile ts -> js
FROM node:10 As builder

WORKDIR /usr/src/app

COPY . .

RUN npm i

RUN npm run build

# Run Nest.js Application in Node Alpine Image
FROM node:14-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app ./

CMD ["npm", "run", "start"]
